### PR TITLE
Fix #27 - Basic support for STYLE blocks

### LINKED ISSUE #27: Style block incorrectly interpreted as cue
Attemping to parse EXAMPLE 3 from https://w3c.github.io/webvtt/#styling gives the following:
```
Line 4: Cue identifier needs to be followed by timestamp.
Line 13: Cue identifier needs to be followed by timestamp.
```

It seems that the header parser misinterpets the style block as a cue.

### PR DESCRIPTION
**Pull request by davemevans**
Parses and collates style blocks from the the input, ignoring those after the first cue or which contain `-->`.

Styles are made available on the `tree` object returned from `parse`, and can be passed as an optional second argument to `serialize`.

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
FWIW: LGTM

**Review by silviapfeiffer — COMMENTED** [review]
I didn't test it, but it looks good and it's something a lot of people have been asking for.

**Comment by emmanent** [comment]
What will it take to merge this PR? I think this would be incredibly useful, since styles are a big selling-point feature for vtt files 🥳

**Review by dontcallmedom — APPROVED** [review]
thanks, and sorry for the long delay in reviewing this!

**Pull request merged**
